# Generated by Django 5.2.1 on 2025-06-10 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treballador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pot_assignar', models.BooleanField(default=False)),
                ('pot_resoldre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Oberta'), ('assigned', 'Assignada'), ('in_progress', 'En progrés'), ('resolved', 'Resoluta'), ('closed', 'Tancada')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencies_assignades', to='incidencies.treballador')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencies_creades', to='incidencies.treballador')),
            ],
        ),
    ]
