# Generated by Django 5.2.1 on 2025-06-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treballador',
            name='pot_assignar',
        ),
    ]
