# Generated by Django 5.2.1 on 2025-06-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencies', '0002_remove_treballador_pot_assignar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treballador',
            name='pot_resoldre',
        ),
        migrations.AddField(
            model_name='treballador',
            name='pot_assignar',
            field=models.BooleanField(default=False),
        ),
    ]
